#!/bin/sh
#
# S40network - Bring up eth0 with DHCP
#

LINK_TIMEOUT=30
CID_PATH="/sys/class/mmc_host/mmc1/mmc1:0001/cid"

set_mac() {
    cid=$(cat "$CID_PATH" 2>/dev/null)
    if [ -z "$cid" ]; then
        echo "S40network: no eMMC CID found, using random MAC"
        return
    fi
    hash=$(echo "$cid" | md5sum | cut -c1-12)
    b1=$(echo "$hash" | cut -c1-2)
    b2=$(echo "$hash" | cut -c3-4)
    b3=$(echo "$hash" | cut -c5-6)
    b4=$(echo "$hash" | cut -c7-8)
    b5=$(echo "$hash" | cut -c9-10)
    b6=$(echo "$hash" | cut -c11-12)
    # Set locally-administered + unicast bits on first byte
    b1=$(printf "%02x" $(( 0x$b1 & 0xfe | 0x02 )))
    mac="$b1:$b2:$b3:$b4:$b5:$b6"
    ip link set dev eth0 address "$mac"
    echo "S40network: eth0 MAC set to $mac (from eMMC CID)"
}

start_lo() {
    ifconfig lo up
}

start_eth() {
    set_mac
    echo "S40network: waiting for eth0 link"
    ifconfig eth0 up

    count=0
    while [ "$(cat /sys/class/net/eth0/carrier 2>/dev/null)" != "1" ]; do
        sleep 1
        count=$((count + 1))
        if [ $count -ge $LINK_TIMEOUT ]; then
            echo "S40network: eth0 no link after ${LINK_TIMEOUT}s"
            return 1
        fi
    done

    echo "S40network: eth0 link detected, starting DHCP"
    dhcpcd -b eth0
}

stop_eth() {
    dhcpcd -k eth0 2>/dev/null
    ifconfig eth0 down 2>/dev/null
}

case "$1" in
    start)
        start_lo
        start_eth
        ;;
    stop)
        stop_eth
        ;;
    restart)
        stop_eth
        sleep 1
        start_eth
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
